version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes: 
      - ./app:/app
    command: >
      sh -c "python ./main.py"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    ports:
      - 5445:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
